api: k3ai.in/v1alpha1
kind: Infra

resources:
- path: "curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.5+k3s2 sh -s - {{extras}}"
  args: "--write-kubeconfig-mode 644 --disable traefik"
  kubeconfig: "/etc/rancher/k3s/k3s.yaml"
  type: shell
  wait: true
  remove: "k3s-uninstall.sh"

